import { create } from 'mathjs';
import {
  deepEqualDependencies,
  equalDependencies,
  largerDependencies,
  addDependencies,
  subtractDependencies,
  multiplyDependencies,
  transposeDependencies,
  identityDependencies,
  detDependencies,
  diagDependencies,
  indexDependencies,
  rangeDependencies,
  absDependencies,
  acosDependencies,
  acoshDependencies,
  asinDependencies,
  asinhDependencies,
  cosDependencies,
  coshDependencies,
  sinDependencies,
  sinhDependencies,
  concatDependencies,
  piDependencies,
  sqrtDependencies,
  squareDependencies,
  zerosDependencies,
  matrixDependencies,
  randomDependencies,
} from 'mathjs';

import type { ConfigOptions, FactoryFunctionMap } from 'mathjs';

const factories: FactoryFunctionMap = {
  deepEqualDependencies,
  equalDependencies,
  largerDependencies,
  addDependencies,
  subtractDependencies,
  multiplyDependencies,
  transposeDependencies,
  identityDependencies,
  detDependencies,
  diagDependencies,
  indexDependencies,
  rangeDependencies,
  absDependencies,
  acosDependencies,
  acoshDependencies,
  asinDependencies,
  asinhDependencies,
  cosDependencies,
  coshDependencies,
  sinDependencies,
  sinhDependencies,
  concatDependencies,
  piDependencies,
  sqrtDependencies,
  squareDependencies,
  zerosDependencies,
  matrixDependencies,
  randomDependencies,
};

const config: ConfigOptions = {
  epsilon: 1e-9,
};

export const {
  larger,
  equal,
  deepEqual,
  add,
  subtract,
  multiply,
  transpose,
  identity,
  det,
  diag,
  index,
  range,
  abs,
  acos,
  acosh,
  asin,
  asinh,
  cos,
  cosh,
  sin,
  sinh,
  concat,
  pi,
  sqrt,
  square,
  zeros,
  matrix,
  random,
} = create(factories, config);
